name: C++ CI with Make

on:
  push:
    branches: [branchHTTPserver]
  pull_request:
    branches: [branchHTTPserver]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Generate configure script
        run: |
          autoreconf --install

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run tests
        run: make check

      - name: Upload test log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-suite.log

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/http_server:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/http_server:latest

