name: Build Debian Package

on:
  push:
    branches:
      - branchAutoPackage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential automake autoconf dpkg-dev

      - name: Build Debian package
        run: |
          autoreconf --install
          ./configure
          dpkg-buildpackage -us -uc

      - name: Save Debian package artifact
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: "../*.deb"

