name: C++ CI with Multiarch Docker Build

on:
  push:
    branches: [branchHTTPservMulti]
  pull_request:
    branches: [branchHTTPservMulti]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Generate configure script
        run: autoreconf --install

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run tests
        run: make check

      - name: Upload test log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-suite.log

      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # тут зберігайте 'olegkhomenko'
          password: ${{ secrets.DOCKER_TOKEN }}

      # Створення образів для двох архітектур
      - name: Build and push for amd64
        run: docker buildx build --platform=linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/optimaserver:amd64 --push .

      - name: Build and push for arm64
        run: docker buildx build --platform=linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/optimaserver:arm64 --push .

      # Створення та пуш мульті-арх маніфесту з правильним ім'ям користувача та латинськими літерами
      - name: Create and push manifest
        run: |
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/optimaserver:latest \
            --amend ${{ secrets.DOCKER_USERNAME }}/optimaserver:amd64 \
            --amend ${{ secrets.DOCKER_USERNAME }}/optimaserver:arm64
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/optimaserver:latest

