name: Run Unit Tests

on:
  push:
    branches:
      - branchAutoTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential automake autoconf g++ libcppunit-dev

      - name: Generate configuration files
        run: autoreconf --install

      - name: Compile tests
        run: |
          ./configure
          make

      - name: Run unit tests
        run: make check

