name: C++ CI with Multiarch Docker Build

on:
  push:
    branches: [branchHTTPservMulti]
  pull_request:
    branches: [branchHTTPservMulti]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клон репозиторію
      - uses: actions/checkout@v4

      # Крок 2: Встановлення залежностей для білду (локальна збірка)
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      # Крок 3: Генеруємо configure
      - name: Generate configure script
        run: autoreconf --install

      # Крок 4: Конфігуруємо
      - name: Configure
        run: ./configure

      # Крок 5: Білд
      - name: Build
        run: make

      # Крок 6: Запуск тестів
      - name: Run tests
        run: make check

      # Крок 7: Якщо тести падають – завантажуємо лог
      - name: Upload test log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-suite.log

      # Крок 8: Налаштування QEMU
      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      # Крок 9: Встановлення Docker Buildx
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Крок 10: Перевірка builder
      - name: build ls
        run: docker buildx ls

      # Крок 11: Логін до Docker Hub
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Крок 12: Білд та пуш образу для amd64
      - name: Build and push for amd64
        run: docker buildx build --platform=linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/optimaserver:amd64 --push .

      # Крок 13: Білд та пуш образу для arm64
      - name: Build and push for arm64
        run: docker buildx build --platform=linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/optimaserver:arm64 --push .

      # Крок 14: Створення мульті-архітектурного маніфесту
      - name: Create manifest
        run: docker manifest create ${{ secrets.DOCKER_USERNAME }}/optimaserver \
             --amend ${{ secrets.DOCKER_USERNAME }}/optimaserver:amd64 \
             --amend ${{ secrets.DOCKER_USERNAME }}/optimaserver:arm64

      # Крок 15: Пуш маніфесту
      - name: Push manifest to docker hub
        run: docker manifest push ${{ secrets.DOCKER_USERNAME }}/optimaserver

