name: C++ CI with Multiarch Docker Build

on:
  push:
    branches: [branchHTTPservMulti]
  pull_request:
    branches: [branchHTTPservMulti]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Generate configure script
        run: autoreconf --install

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run tests
        run: make check

      - name: Upload test log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-suite.log

      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls

      - name: Log in to dockerhub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      # Побудова та пуш образу для amd64
      - name: Build and push for amd64
        run: docker buildx build --platform=linux/amd64 -t ${{ vars.DOCKER_USERNAME }}/optimaserver:amd64 --push .

      # Побудова та пуш образу для arm64
      - name: Build and push for arm64
        run: docker buildx build --platform=linux/arm64 -t ${{ vars.DOCKER_USERNAME }}/optimaserver:arm64 --push .

      # Створення мульті-арх маніфесту
      - name: Create manifest
        run: docker manifest create ${{ vars.DOCKER_USERNAME }}/optimaserver \
             --amend ${{ vars.DOCKER_USERNAME }}/optimaserver:amd64 \
             --amend ${{ vars.DOCKER_USERNAME }}/optimaserver:arm64

      # Пуш мульті-арх маніфесту
      - name: Push manifest to docker hub
        run: docker manifest push ${{ vars.DOCKER_USERNAME }}/optimaserver

