name: C++ CI with Multiarch Docker Build

on:
  push:
    branches: [branchHTTPservMulti]
  pull_request:
    branches: [branchHTTPservMulti]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Generate configure script
        run: autoreconf --install

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run tests
        run: make check

      - name: Upload test log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-suite.log

      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: olegkhomenko
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push for amd64
        run: |
          docker buildx build --platform=linux/amd64 --load \
          -t olegkhomenko/http_server:amd64 .
          docker push olegkhomenko/http_server:amd64

      - name: Build and push for arm64
        run: |
          docker buildx build --platform=linux/arm64 --load \
          -t olegkhomenko/http_server:arm64 .
          docker push olegkhomenko/http_server:arm64

      - name: Create manifest
        run: |
          echo "Creating manifest list for http_server..."
          docker manifest create olegkhomenko/http_server \
            --amend olegkhomenko/http_server:amd64 \
            --amend olegkhomenko/http_server:arm64
          echo "Manifest creation completed. Inspecting manifest:"
          docker manifest inspect olegkhomenko/http_server

      - name: Push manifest to Docker Hub
        run: |
          echo "Pushing manifest list to Docker Hub..."
          docker manifest push olegkhomenko/http_server
          echo "Manifest pushed successfully."

